create table foo (
  id bigint generated by default as identity (start with 1),
  name varchar(100) not null,
  primary key(id)
);

create table works (
    id bigint generated by default as identity (start with 1),
    name varchar(50) not null,
    description varchar(5000) not null,
    primary key(id)
);